version: '2'

services:
  psqldb:
    image: postgres
    ports:
      - "8002:5432"
    volumes:
      - ./psqldb:/docker-entrypoint-initdb.d/
  neo4jdb:
    image: neo4j
    ports:
     - "8003:7474"
     - "8004:7687"
    volumes:
       - ./neo4jdb/data:/data
       - ./neo4jdb/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/neo4jpass
  taskit:
    build: .
    command: ./docker-entrypoint.sh
    volumes:
      - .:/TasKit
    ports:
      - "8001:8000"
    depends_on:
      - psqldb
      - neo4jdb