version: '2'

services:
  psqldb:
    image: postgres
    ports:
      - "8002:5432"
    volumes:
      - ./psqldb:/var/lib/postgresql/data
  neo4jdb:
    image: neo4j
    ports:
     - "8003:7474"
     - "8004:7687"
    volumes:
       - ./neo4jdb/data:/data
       - ./neo4jdb/logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/neo4jpass
  taskit:
    build: .
    image: taskit
    command: ./docker-entrypoint.sh
    volumes:
      - .:/TasKit
    ports:
      - "8001:8000"
    depends_on:
      - psqldb
      - neo4jdb
  chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444"
  test:
    build: .
    image: taskit
    command: sh test_entry.sh
    volumes:
      - .:/TasKit
    depends_on:
      - chrome